TYPE_OPTIONS = ["Manufactured", "Purchased", "Sales Kit"]
ON_HOLD_REASON_OPTIONS = [
    "Engineering - In-Process",
    "Engineering prototype",
    "Engineering Review Needed",
    "Marketing Updates",
    "Materials - FTT Review needed",
    "MOM Detail Review",
    "New Part - Needs review",
    "No Converted MOM",
    "Obsolete - Slow Moving Inv.",
    "Obsolete Part",
    "Part End of Life"
]
GROUP_OPTIONS = [
    "_COMP - Component parts",
    "_CSUP - Cust. Supplied",
    "_CUST - Custom parts",
    "_DIST - Distributed parts",
    "_ENCL - Standard - Enclosure",
    "_EWARR Service - Ext. Warranty",
    "_FS-EPD -Service - Field - EPD",
    "_FS-MPD -Service - Field - MPD",
    "_HG7 - Technical - HG7 Panels",
    "_HG7-Kit - HG7 Kits",
    "_HGA-Technical-Active Filters",
    "_HGA - Technical - HGL Panels",
    "_HGL-KIT-Technical-HGL Kits",
    "_HGP - Technical - HGP Panels",
    "_HGP-KIT-Technical-HGP Kits",
    "_HSD-Technical-Harmonicshield",
    "_HSE",
    "_HSE-KIT - HSE Kits",
    "_HSL",
    "_KDR - Standard KDR",
    "_KDRL - KDRL",
    "_KDRTT - Standard KDRTT",
    "_KDRX - Standard KDRX",
    "_KLC - Standard - KLC",
    "_KLR - Standard - KLR",
    "_KMG - Technical - KMG",
    "_KRF",
    "_KTR - Standard - KTR",
    "_MFC - Technical - MFC",
    "_MSD - Technical - Motorshield",
    "_OBSDIST - Obsolete - DIST",
    "_OBSHF - Obsolete - HF",
    "_PASSIVE - Standard - Passive",
    "_PFG - Technical - PF Guard",
    "_R&D - R&D parts - Not Sold",
    "_V1K - Standard - V1K",
    "_V1K-KIT"
]
CLASS_OPTIONS = [
    "_FG - Custom Products",
    "_FG - Distributed Products",
    "_FG - Electronic Products",
    "_FG - Harmonic Filter",
    "_FG - Output Filters",
    "_FG - Power Factor Correction",
    "_FG - Reactors",
    "_FG - Sinewave Filter",
    "Assembly",
    "Core",
    "Electrical",
    "Enclosures",
    "Extended Warranty - EPD",
    "Extended Warranty - MPD",
    "Fabricated Parts",
    "Field Service - EPD",
    "Hardware",
    "Insulators",
    "Labels",
    "Literature",
    "Miscellaneous",
    "Packaging",
    "R&D EPD parts",
    "Raw Metallic",
    "Shop Supplies",
    "Terminals",
    "Winding Conductors"
]
LABEL_GROUP_OPTIONS = [
    "EHFB",
    "EHFT",
    "EPF",
    "GE Oil and Gas Assembly",
    "HG",
    "HG7",
    "HarmonicGuard Low Capacitance Filter",
    "HarmonicGuard Passive Filter",
    "HarmonicShield",
    "HSE",
    "HSL",
    "KCAP",
    "KDR",
    "KDRUL",
    "KHG",
    "KLC",
    "KLCUL",
    "KLR",
    "KLRUL",
    "KMG",
    "KPC Capacitor Bank",
    "KTR",
    "KTRUL",
    "MFC",
    "MotorShield",
    "PCB",
    "PF Guard",
    "PUR or ENCL (box label only)",
    "V1K"
]
REPORTING_GROUP_OPTIONS = [
    "_COMP - Component parts",
    "_CSUP - Cust. Supplied",
    "_CUST - Custom parts",
    "_DIST - Distributed parts",
    "_ENCL - Standard - Enclosure",
    "_EPF",
    "_EWARR Service - Ext. Warranty",
    "_FS-EPD -Service - Field - EPD",
    "_FS-MPD -Service - Field - MPD",
    "_HG7 - Technical - HG7 Panels",
    "_HG7-KIT - HG7 Kits",
    "_HGA-Technical-Active Filters",
    "_HGL - Technical - HGL Panels",
    "_HGL-KIT-Technical-HGL Kits",
    "_HGP - Technical - HGP Panels",
    "_HGP-KIT-Technical-HGP Kits",
    "_HSD-Technical-Harmonicshield",
    "_KDR - Standard KDR",
    "_KDRTT - Standard KDRTT",
    "_KLC - Standard - KLC",
    "_KLR - Standard - KLR",
    "_KMG - Technical - KMG",
    "_KTR - Standard - KTR",
    "_MFC - Technical - MFC",
    "_MSD - Technical - Motorshield",
    "_OBSDIST - Obsolete - DIST",
    "_OBSHF - Obsolete - HF",
    "_PASSIVE - Standard - Passive",
    "_PFG - Technical - PF Guard",
    "_R&D - R&D parts - Not Sold",
    "_V1K - Standard - V1K"
]